### ISSUE TITLE
Add an options to use django-tables

### ISSUE THREAD

**Issue by Tobi-De** [falcopackages/falco-cli#59]
https://github.com/jieter/django-tables2

Add via crud configuration an option to use django_tables2

```toml
[tool.falco.crud]
use-django-tables2 = true
```
